[package]
name = "kosim_player"
version = "0.1.0"
edition = "2024"
license = "Apache-2.0"

[dependencies]
bevy_camera = "0.17.3"
bevy_ecs = "0.17.3"
bevy_input = "0.17.3"
bevy_math = "0.17.3"
bevy_time = "0.17.3"
bevy_transform = "0.17.3"
kosim_input = { version = "0.1.0", path = "../kosim_input" }
kosim_utility = { version = "0.1.0", path = "../kosim_utility" }
