[package]
name = "kosim_input"
version = "0.1.0"
edition = "2024"

[dependencies]
bevy_ecs = "0.17.3"
bevy_input = "0.17.3"
bevy_math = "0.17.3"
bevy_window = "0.17.3"
kosim_utility = { version = "0.1.0", path = "../kosim_utility" }
